export const SWITCH_SECTION = 'SWITCH_HOME_SECTION';

export const SET_ACTIVE_SECTION = 'SET_ACTIVE_SECTION';

export const TOGGLE_NAV = 'TOGGLE_HOME_NAV';

export const EXTEND_PORTFOLIO_SECTION = 'EXTEND_PORTFOLIO_SECTION';

export const TOGGLE_SKILLS_ROW = 'TOGGLE_SKILLS_ROW';

export const LOAD_PORTOFOLIO_IMAGES = 'LOAD_PORTOFOLIO_IMAGES';

export const UNSET_SCROLL_TRIGGERED = 'UNSET_SCROLL_TRIGGERED';
