export const SWITCH_SECTION = 'SWITCH_HOME_SECTION';

export const TOGGLE_NAV = 'TOGGLE_HOME_NAV';

export const EXTEND_PORTFOLIO_SECTION = 'EXTEND_PORTFOLIO_SECTION';

export const TOGGLE_SKILLS_ROW = 'TOGGLE_SKILLS_ROW';

